api/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin/account', class_name: 'AdminUser', skip: %I[registrations]

  namespace :admin do
    resources :admin_users
    resources :roles
    resources :users do
      resources :points, only: %i[index] do
        post :export, on: :collection
      end

      resources :discounts, controller: 'users/discounts', only: %i[index] do
        patch :refresh, on: :collection
      end
    end
    resources :segments
    resources :banking_infos, except: [:index]
    resources :products
    resources :discounts
    resources :uploaded_tickets, only: %i[index show] do
      member do
        post :review
      end
    end
    resources :reviewed_tickets, only: %i[index show] do
      member do
        post :recreate
      end
    end
    resources :digitalized_tickets, only: %i[index show] do
      member do
        post :review
      end
    end
    resources :unsegmented_tickets, only: %i[index show] do
      member do
        post :assign_segments
      end
    end
    resources :pending_payments, only: %i[index] do
      collection do
        post :export
      end
    end
    resources :tickets, only: [:index, :show]
    resource :database, only: %i[show], controller: 'database' do
      post :export
      get :import_user_segments, to: 'database#show_import_user_segments'
      post :import_user_segments
    end
    resource :async_database, only: %i[show destroy], controller: 'async_database' do
      post :export
      patch :cancel
      patch :download
    end
    resources :push_notifications, only: %i[new create] do
      collection do
        post :create_segment_notification
      end
    end
    resources :rewards, only: %i[new create]
    resources :audits, only: %i[new create]
    root to: 'users#index'
  end

  get 'not_authorized', to: 'application#not_authorized'

  devise_scope :user do
    get 'unlocked', as: 'unlocked', to:'api/v1/overrides/unlocks#unlocked'
    get 'overrides/unlocks/unlocked_failure', as: 'unlocked_failure', to: 'api/v1/overrides/unlocks#unlocked_failure'
  end

  mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
    sessions: 'api/v1/overrides/sessions',
    registrations: 'api/v1/overrides/registrations',
    confirmations: 'api/v1/overrides/confirmations',
    passwords: 'api/v1/overrides/passwords',
    unlocks: 'api/v1/overrides/unlocks'
  }

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: %I[update]
      resources :banking_infos, only: %I[create update]
      resources :tickets, only: %I[create index]
      resources :user_discounts, only: %I[index]
      get 'user_discounts/obtained_discounts'
      get 'points/current_points'
      get 'points/history'
      get 'users/show'
      get 'discounts/landing_discounts'
      get 'discounts/show'
      get 'products/index'
      devise_scope :user do
        get 'auth/confirmed', controller: 'api/v1/overrides/confirmations', action: 'confirm'
      end
    end
  end

  devise_scope :user do
    get 'omniauth/confirmed', controller: 'api/v1/overrides/confirmations', action: 'confirm'
  end

  mount Sidekiq::Web, at: 'sidekiq'
end

api/app/controllers/admin/async_database_controller.rb
module Admin
  class AsyncDatabaseController < Admin::ApplicationController
    def show
      resource = AsyncExport.new(admin_user: current_admin_user)
      authorize resource, :export?, policy_class: DatabasePolicy
      render action: :show, locals: render_locals_for(resource)
    end

    def export
      resource = AsyncExport.new(admin_user: current_admin_user)
      authorize resource, policy_class: DatabasePolicy
      return render_limit_error(resource) if export_limit_reached?
      return render_export_errors(resource) unless resource.save

      perform_export(resource)
    end

    def download
      authorize resource, :export?, policy_class: DatabasePolicy
      unless File.exist?(resource.filename)
        flash[:error] = I18n.t('admin.messages.database.async.download.error')
        resource&.destroy
        return redirect_to action: :show
      end
      send(:send_file, resource.filename)
    end

    def destroy
      authorize resource, :export?, policy_class: DatabasePolicy
      result = nil
      AsyncExport.transaction do
        result = resource&.destroy ? :notice : :error
        flash[result] = I18n.t("admin.messages.database.async.destroyed.#{result}")
      end
      redirect_to action: :show
    end

    private

    def resource
      @resource ||= AsyncExport.find_by(id: params.require(:request_id))
    end

    def render_limit_error(resource)
      flash[:error] = I18n.t(
        'admin.errors.database.export_async.limit_reached', limit: export_limit
      )
      render_export_errors(resource)
    end

    def render_export_errors(resource)
      render action: :show,
             locals: render_locals_for(resource),
             status: :unprocessable_entity
    end

    def perform_export(resource)
      CreateDatabaseBackup.perform_async(resource.id)
      flash[:notice] = I18n.t('admin.messages.database.export_async.success')
      redirect_to action: :show
    end

    def export_limit_reached?
      AsyncExport.in_process.count >= export_limit
    end

    def export_limit
      Rails.application.secrets.async_export_limit
    end

    def render_locals_for(resource)
      {
        page: Administrate::Page::Show.new(nil, resource),
        in_process: AsyncExport.in_process,
        available: AsyncExport.available,
        export_limit: export_limit,
        export_days: Rails.application.secrets.database_backup_storage_time
      }
    end
  end
end

api/app/views/admin/async_database/show.html.slim
- content_for(:title) do
  = t("admin.actions.database.export")
header.main-content__header role="banner"
  h1.main-content__page-title
    = t("admin.actions.database.export")
section.main-content__body
  = form_for page.resource, url: export_admin_async_database_url, method: :post, html: { class: 'form' } do |f|
    p = t('admin.actions.database.async_warning', limit: export_limit)
    hr
    .form-actions
      = f.submit t("admin.actions.database.async_request"), data: { disable_with: false }
  hr
  h2 = t('admin.messages.database.export_async.in_process')
  - if in_process.count.zero?
    p = t('admin.messages.database.export_async.none')
  - else
    table
      thead
        tr
          th = t('activerecord.attributes.async_export.created_at')
          th = t('activerecord.attributes.async_export.admin_user')
      tbody
        - in_process.each do |export|
          tr
            td = I18n.localize(export.created_at)
            td
              a href=admin_admin_user_path(export.admin_user)
                = export.admin_user.name
  hr
  h2 = t('admin.messages.database.export_async.ready')
  p = t('admin.actions.database.async_remove_warning', days: export_days, next_days: export_days + 1)
  - if available.count.zero?
    p = t('admin.messages.database.export_async.none')
  - else
    table
      thead
        tr
          th = t('activerecord.attributes.async_export.created_at')
          th = t('activerecord.attributes.async_export.admin_user')
          th = t('activerecord.attributes.async_export.actions')
      tbody
        - available.each do |export|
          tr
            td = I18n.localize(export.created_at)
            td
              a href=admin_admin_user_path(export.admin_user)
                = export.admin_user.name
            td style="display:flex"
              = form_for export, url: download_admin_async_database_path(request_id: export.id) do |f|
                = f.submit t('activerecord.attributes.async_export.download'), data: { disable_with: false }
              div = '&nbsp;'.html_safe
              = form_for export, url: admin_async_database_path(request_id: export.id), method: :delete do |f|
                = f.submit t('activerecord.attributes.async_export.destroy'), class: 'button danger'