api/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin/account', class_name: 'AdminUser', skip: %I[registrations]

  namespace :admin do
    resources :admin_users
    resources :roles
    resources :users do
      resources :points, only: %i[index] do
        post :export, on: :collection
      end

      resources :discounts, controller: 'users/discounts', only: %i[index] do
        patch :refresh, on: :collection
      end
    end
    resources :segments
    resources :banking_infos, except: [:index]
    resources :products
    resources :discounts
    resources :uploaded_tickets, only: %i[index show] do
      member do
        post :review
      end
    end
    resources :reviewed_tickets, only: %i[index show] do
      member do
        post :recreate
      end
    end
    resources :digitalized_tickets, only: %i[index show] do
      member do
        post :review
      end
    end
    resources :unsegmented_tickets, only: %i[index show] do
      member do
        post :assign_segments
      end
    end
    resources :pending_payments, only: %i[index] do
      collection do
        post :export
      end
    end
    resources :tickets, only: [:index, :show]
    resource :database, only: %i[show], controller: 'database' do
      post :export
      get :import_user_segments, to: 'database#show_import_user_segments'
      post :import_user_segments
    end
    resource :async_database, only: %i[show destroy], controller: 'async_database' do
      post :export
      patch :cancel
      patch :download
    end
    resources :push_notifications, only: %i[new create] do
      collection do
        post :create_segment_notification
      end
    end
    resources :rewards, only: %i[new create]
    resources :audits, only: %i[new create]
    root to: 'users#index'
  end

  get 'not_authorized', to: 'application#not_authorized'

  devise_scope :user do
    get 'unlocked', as: 'unlocked', to:'api/v1/overrides/unlocks#unlocked'
    get 'overrides/unlocks/unlocked_failure', as: 'unlocked_failure', to: 'api/v1/overrides/unlocks#unlocked_failure'
  end

  mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
    sessions: 'api/v1/overrides/sessions',
    registrations: 'api/v1/overrides/registrations',
    confirmations: 'api/v1/overrides/confirmations',
    passwords: 'api/v1/overrides/passwords',
    unlocks: 'api/v1/overrides/unlocks'
  }

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: %I[update]
      resources :banking_infos, only: %I[create update]
      resources :tickets, only: %I[create index]
      resources :user_discounts, only: %I[index]
      get 'user_discounts/obtained_discounts'
      get 'points/current_points'
      get 'points/history'
      get 'users/show'
      get 'discounts/landing_discounts'
      get 'discounts/show'
      get 'products/index'
      devise_scope :user do
        get 'auth/confirmed', controller: 'api/v1/overrides/confirmations', action: 'confirm'
      end
    end
  end

  devise_scope :user do
    get 'omniauth/confirmed', controller: 'api/v1/overrides/confirmations', action: 'confirm'
  end

  mount Sidekiq::Web, at: 'sidekiq'
end

api/app/models/application_view.rb
class ApplicationView < ApplicationRecord
  self.abstract_class = true

  def readonly?
    true
  end
end

api/app/models/user.rb
class User < ApplicationRecord
  devise :registerable,
         :lockable,
         :trackable,
         :database_authenticatable,
         :password_archivable,
         :secure_validatable,
         :recoverable,
         :timeoutable

  # BUG: should be included AFTER devise modules or it causes a bug in registrations
  include DeviseTokenAuth::Concerns::User
  # Added as a concern to share configurations.
  include Concerns::Auditable

  enum gender: { unknown: 0, male: 1, female: 2 }

  validates :name, :gender, presence: true, length: { in: 1..90 }
  validates :birthday, presence: true, age: true
  validates :email, uniqueness: { scope: :provider, case_sensitive: false }
  validates :avatar, body_size: true, image: true
  validates :dni, numericality: { only_integer: true }, allow_nil: true
  validates :dni, uniqueness: true

  has_one :banking_info, dependent: :destroy
  has_one :device, dependent: :destroy
  has_many :daily_points, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :user_discounts, -> { with_deleted }, inverse_of: :user
  has_many :ticket_discounts, through: :tickets
  has_many :discounts, through: :user_discounts
  has_many :user_segments, dependent: :destroy
  has_and_belongs_to_many :segments, dependent: :destroy, join_table: 'user_segments'
  has_many :received_notifications, class_name: 'PushNotificationLog',
                                    foreign_key: :recipient_id,
                                    inverse_of: :recipient,
                                    dependent: :nullify

  accepts_nested_attributes_for :banking_info
  accepts_nested_attributes_for :segments

  has_one_attached :avatar

  scope :for_point_calculation, -> { includes(:rewards, user_discounts: %i[discount]) }

  scope :inactive, lambda {
    includes(:device)
      .where("(SELECT max(value ->> 'expiry') FROM json_each(tokens)) < ?", 1.week.ago.to_i.to_s)
  }

  def self.xls_columns
    column_names + ['current_points', I18n.t('activerecord.general.attributes.deleted_status')]
  end

  # Added current_points as an attribute to be displayed in Administrate
  attribute(:current_points)
  def current_points
    Points::CurrentPointsCalculator.current_points(self)
  end

  # Overriding Devise method so it can be queued in Sidekiq
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  # Only way to set custom texts in administrate's collection selects
  def selection_format
    I18n.t('activerecord.formats.user.selection', id: id, name: name, email: email)
  end

  def user_discounts_without_exchange
    user_discounts.where.not(discount_id: exchanged_discounts_ids)
  end

  protected

  # Users do not require confirmation, up to specific point
  def confirmation_required?
    false
  end

  private

  def exchanged_discounts_ids
    ticket_discounts.where(active: true).where.not(discount_id: nil).pluck(:discount_id)
  end
end

api/app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    SINGULAR_COUNT = 1

    include Administrate::Punditize
    before_action :authenticate_admin_user!

    # Allow audited to use a custom user based on the controller
    def audited_user
      current_admin_user
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    def after_sign_in_path_for(user)
      user.has_any_role?(:admin, :super_admin) ? admin_root : super
    end

    def after_sign_out_path_for(scope)
      case scope
      when :user
        new_user_session_path
      when :admin_user
        new_admin_user_session_path
      else
        super
      end
    end

    # Required by Administrate
    def admin_old_passwords_path
      admin_user_password_path
    end

    def pundit_user
      current_admin_user
    end

    # This is used by Administrate to display actions.
    # The original code for some odd reason didn't use active record keys for translations
    def translate_with_resource(key)
      t(
        "administrate.controller.#{key}",
        resource: translated_resource
      )
    end

    def translated_resource
      t("activerecord.models.#{resource_class.model_name.i18n_key}", count: SINGULAR_COUNT)
    end
  end
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def not_authorized; end

  protected

  def user_not_authorized
    redirect_to '/not_authorized'
  end

  def configure_permitted_parameters
    attributes = %i[birthday name gender avatar last_name dni]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(_resource_or_scope)
    admin_root_path
  end
end

api/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
    PLACEHOLDER_URL = Rails.application.secrets.placeholder_url.freeze

    def navbar_link_to(path, &block)
      classes = "sidebar__link sidebar__link--#{current_page?(path) ? 'active' : 'inactive'}"
      link_to(path, class: classes, &block)
    end

    def resource_icon_for(resource)
      dashboard_for(resource).resource_icon
    end

    def dashboard_for(resource)
      @dashboards ||= {}
      @dashboards[resource.name] ||= "#{resource.to_s.classify}Dashboard".constantize.new
    end

    def attachment_url_for(attachment, **kwargs)
      attachment.attached? ? url_for(attachment) : placeholder_url(**kwargs)
    end

    def placeholder_url(width: 640, height: width, foreground: '333333', background: 'CCCCCC')
      "#{PLACEHOLDER_URL}/#{width}x#{height}/#{background}/#{foreground}.png"
    end

    def available_segments
      @available_segments ||= Segment.all
    end

    def format_discount(discount)
      "#{discount.discount_type} #{discount.title} #{discount.description}"
    end

    def in_sidebar?(resource)
      return false if resource.blank?

      policy_for(class_from_resource(resource))&.index?
    # This case applies for example, to, for example push notifications because they are
    # in the router but they don't have a model attached.
    rescue StandardError
      false
    end

    def policy_for(resource)
      Pundit.policy(pundit_user, resource)
    end
  end
end

api/app/views/admin/application/_assign_segments_form.html.slim
= form_for page.resource.user, url: { action: :assign_segments }, method: :post do |f|
  .field-unit__relationship
    = f.label :segments
    .checkbox-grid
      = f.collection_check_boxes(:segment_ids, available_segments, :id, :name)
  hr
  .form-actions
    = f.submit t('admin.actions.unsegmented_tickets.assign_segments')

api/app/views/admin/application/_collection.html.slim
table aria-labelledby=table_title
  thead
    tr
      - collection_presenter.attribute_types.each do |attr_name, attr_type|
        th 
          .cell-label class="cell-label--header cell-label--#{attr_type.html_class} cell-label--#{collection_presenter.ordered_html_class(attr_name)}" scope='col' role='columnmheader' aria-sort=sort_order(collection_presenter.ordered_html_class(attr_name))
            = link_to sanitized_order_params(page, collection_field_name).merge(collection_presenter.order_params_for(attr_name, key: collection_field_name))
              = t( \
                  "activerecord.attributes.#{collection_presenter.resource_name}.#{attr_name}", \
                  default: attr_name.to_s, \
                ).titleize
              - if collection_presenter.ordered_by?(attr_name)
                span class=("cell-label__sort-indicator cell-label__sort-indicator--#{collection_presenter.ordered_html_class(attr_name)}") 
                  svg aria-hidden="true" 
                    use xlink:href="#icon-up-caret" 

      - [valid_action?(:edit, collection_presenter.resource_name), valid_action?(:destroy, collection_presenter.resource_name)].count(true).times
        th scope="col"

  tbody
    - resources.each do |resource|
      tr class='js-table-row' tabindex='0'
        - if valid_action? :show, collection_presenter.resource_name
          tr.js-table-row tabindex="0" role="link" data-url=polymorphic_path([namespace, resource])
            - collection_presenter.attributes_for(resource).each do |attribute|
              td class="cell-data cell-data--#{attribute.html_class}"
                - if show_action? :show, resource
                  a.action-show href="#{polymorphic_path([namespace, resource])}"
                    = render_field attribute
            - if valid_action? :edit, collection_presenter.resource_name
              td
                = link_to( t("administrate.actions.edit"), [:edit, namespace, resource], class: "action-edit") if show_action? :edit, resource
            - if valid_action? :destroy, collection_presenter.resource_name
              td
                = link_to( t("administrate.actions.destroy"), [namespace, resource], method: :delete, data: { confirm: t("administrate.actions.confirm") }, class: "text-color-red") if show_action? :destroy, resource

api/app/views/admin/application/_form-submit.html.slim
= f.submit

api/app/views/admin/application/_form.html.slim
= form_for([namespace, page.resource], html: { class: "form" }) do |f|
  .field-grid
    - page.attributes.each do |attribute|
      = render_field attribute, f: f
  .form-actions
    = render partial: 'form-submit', locals: { f: f }

api/app/views/admin/application/_javascript.html.slim
- Administrate::Engine.javascripts.each do |js_path|
  = javascript_include_tag js_path

= yield :javascript
= yield :javascript_includes

= javascript_include_tag :application

script = ("I18n.defaultLocale='".html_safe + I18n.default_locale + "';I18n.locale='".html_safe + I18n.locale + "';".html_safe)

- if Rails.env.test?
  = javascript_tag do
    = "$.fx.off = true;"
    = "$.ajaxSetup({ async: false });"

api/app/views/admin/application/_navigation.html.slim
nav.navigation role="navigation"
  h1.navigation__title
    = "Administrador de tickets - #{content_for(:title)}"
  .navigation__user_menu
    span.navigation__text = t('administrate.navigation.messages.hello', name: current_admin_user.name)
    = link_to t('administrate.actions.sign_out'), destroy_admin_user_session_path, method: :delete, class: "navigation__link"

api/app/views/admin/application/_reject_reasons_modal.html.slim
.reject-reason_link
  a.link  href="#" data-target="reject-reason-#{td.object.id}" data-toggle="modal" = "(#{t('activerecord.actions.ticket_discount.reject_reason')})"

.content-modal id="reject-reason-#{td.object.id}"
  .modal-window
    span.close data-dismiss="modal"  &times;
    h3 = t('activerecord.actions.ticket_discount.reject_reason')
    hr
    = td.text_field :reject_reason

api/app/views/admin/application/_reject_ticket.html.slim
= form_for(resource, url: { action: :review }, method: 'POST', html: { class: "form quick-review" }) do |f|
  h2 = t('activerecord.forms.ticket.reject.title')
  .form-actions = t('activerecord.messages.ticket.uploaded', count: resource.daily_counter)
  - if resource.first_ticket?
    .form-actions = t('activerecord.messages.ticket.first_one')
  .form-actions = 
  hr
  .field-grid
    = f.hidden_field :status, class: 'status-input'
    = f.hidden_field :reason_message, class: 'reason-message-input'
    = f.label :ticket_code
    .field-unit__field
      = f.text_field :ticket_code
      = render "field_errors", field: :ticket_code, f: f
    = f.label :emitted_at
    .field-unit__field
      = f.datetime_field :emitted_at, as: :datetime
      = render "field_errors", field: :emitted_at, f: f
    = f.fields_for Reward.new do |reward|
      = reward.label :points, class: 'field-unit__label'
      .field-unit__field
        = reward.number_field :points, value: 0, min: 0, max: Rails.application.secrets.boost_points_limit
        .field-unit__helper
          = t('admin.helpers.uploaded_tickets.points')
  .form-actions.form-actions--row
    - if policy_for(resource).reject?
      button.button.danger data-target="reject" data-toggle="modal" = t('activerecord.actions.ticket.reject')
    - if policy_for(resource).accept?
      button data-target="accept" data-toggle="modal" = t('activerecord.actions.ticket.accept')

#accept.content-modal
  .modal-window
    span.close data-dismiss="modal"  &times;
    h3 = t('activerecord.actions.ticket.accept_modal')
    hr
    input.accept-reason
    br
    button.accept_ticket = t('activerecord.actions.ticket.accept')

#reject.content-modal
  .modal-window
    span.close data-dismiss="modal"  &times;
    h3 = t('activerecord.actions.ticket.reject_modal')
    hr
    select.reject-reason
      - Ticket::REJECTED_STATUSES.each do |status|
        option value="#{status}" = t("activerecord.enums.ticket.status.#{status}")
    br
    button.button.danger.reject_ticket = t('activerecord.actions.ticket.reject')

= content_for :javascript_includes do
  = javascript_include_tag "admin/forms/modal.js"

api/app/views/admin/application/_role_permissions.html.slim
.role-permissions
  - f.object.permission_sets.each do |set|
    .role-permissions__group class="role-permissions__#{set}"
      h3 = t("activerecord.models.#{set}", count: 1000000)
      .role-permissions__fields
        - f.object.permissions_for(set).each do |permission|
          = f.check_box permission, disabled: disabled
          = f.label permission, t("activerecord.attributes.permissions.#{permission}")

api/app/views/admin/application/_segment_fields.html.slim
tr.nested-fields
  td.form-field
    = f.text_field :name
    = render("field_errors", field: :name, f: f)
  td.form-field
    = link_to_remove_association "×", f, class: 'button remove-element'

api/app/views/admin/application/_sidebar.html.slim
ul#sidebar.sidebar.sidebar__show
  - Administrate::Namespace.new(namespace).resources.each do |resource|
    - # BUGFIX: Using class_from_resource is required to make index? work with pundit
    - if in_sidebar?(resource)
      li.sidebar__item
        = link_to([namespace, resource_index_route_key(resource)], class: "sidebar__link sidebar__link--#{nav_link_state(resource)}") do
          i.fa.fa-fw class="fa-#{resource_icon_for(resource)}"
          .sidebar__text
            = display_resource_name(resource)
          .sidebar__item__badge = class_from_resource(resource).all.count
  - # valid_action? does not work when not using resources and policy(pundit_user, Database) attempts to get "ModulePolicy"
  - if DatabasePolicy.new(pundit_user, nil).show?
    li.sidebar__item
      = navbar_link_to(admin_database_path) do
        i.fa.fa-fw.fa-download
        .sidebar__text = t('admin.actions.database.export')
    li.sidebar__item
      = navbar_link_to(admin_async_database_path) do
        i.fa.fa-fw.fa-download
        .sidebar__text = t('admin.actions.database.export_async')
  - if AuditPolicy.new(pundit_user, nil).new?
    li.sidebar__item
      = navbar_link_to(new_admin_audit_path) do
        i.fa.fa-fw.fa-download
        .sidebar__text = t('admin.actions.audits.create')
  - if PushNotificationPolicy.new(pundit_user, nil).new?
    li.sidebar__item
      = navbar_link_to(new_admin_push_notification_path) do
        i.fa.fa-fw.fa-envelope
        .sidebar__text = t('admin.actions.push_notifications.send')
  - if RewardPolicy.new(pundit_user, nil).create?
    li.sidebar__item
      = navbar_link_to(new_admin_reward_path) do
        i.fa.fa-fw.fa-trophy
        .sidebar__text = t('admin.actions.rewards.create')
  - if DatabasePolicy.new(pundit_user, nil).show_import_user_segments?
    li.sidebar__item
      = navbar_link_to(import_user_segments_admin_database_path) do
        i.fa.fa-fw.fa-upload
        .sidebar__text = t('admin.actions.database.import.user_segments')
  - # used as empty spacing
  li.sidebar__item.sidebar__spacing
.sidebar__action
  button#sidebar-action.sidebar__action__button
    i.fa.fa-fw.fa-fh.fa-chevron-left

api/app/views/admin/application/_ticket_information.html.slim
dl.attribute-set
  - page.attributes.each do |attribute|
    dt.attribute-label id=attribute.name
      = t("activerecord.attributes.#{resource_name}.#{attribute.name}", default: attribute.name.titleize)
    dd class="attribute-data attribute-data--#{attribute.html_class}"
      = render_field attribute, page: page
hr
h3 = t("activerecord.attributes.#{resource_name}.ticket_lines")
table
  thead
    tr
      th = t('activerecord.attributes.ticket_line.product')
      th = t('activerecord.attributes.ticket_line.amount')
      th = t('activerecord.attributes.ticket_line.price')
      th = t('activerecord.attributes.ticket_line.discount_price')
  tbody
    - page.resource.ticket_lines.each do |line|
      tr
        td data-target=line.product.code data-toggle="modal" = line.product.code
        td data-target=line.product.code data-toggle="modal" = line.amount
        td data-target=line.product.code data-toggle="modal" = line.price.format
        td data-target=line.product.code data-toggle="modal" = line.discount_price.format
        .content-modal id=line.product.code
          .modal-window
            span.close data-dismiss="modal"  &times;
            h3.product-modal-title = "Producto " + line.product.code
            hr
            p 
              span 
                b Código: 
              span = line.product.code
            p 
              span 
                b Nombre: 
              span = line.product.name
            p 
              span 
                b Categoría: 
              span = line.product.category
            p 
              span 
                b Proveedor: 
              span = line.product.provider

= content_for :javascript_includes do
  = javascript_include_tag "admin/forms/modal.js"

api/app/views/admin/application/_ticket_line_fields.html.slim
tr.nested-fields
  td.form-field
    button.add-product-btn href="#" data-toggle="modal" Agregar
    .content-modal
      .modal-window
        span.close data-dismiss="modal"  &times;
        h3.product-modal-title Agregar producto
        hr
        = f.fields_for :product, f.object.product || Product.new do |builder|
          = builder.label :code
          = builder.text_field :code, class: 'products-autocomplete'
          = render("field_errors", field: :code, f: builder)
          br
          = builder.label :name
          = builder.text_field :name
          br
          = builder.label :category
          = builder.text_field :category
          br
          = builder.label :provider
          = builder.text_field :provider
        br
        button.button.modal-product-button data-dismiss='modal' Agregar Producto
  td.form-field
    = f.number_field :amount, step: 1
    = render("field_errors", field: :amount, f: f)
  td.form-field
    = f.number_field :price, step: :any, value: f.object.price.to_f
    = render("field_errors", field: :price, f: f)
    = render("field_errors", field: :price_cents, f: f)
    = render("field_errors", field: :price_currency, f: f)
  td.form-field
    = f.number_field :discount_price, step: :any, value: f.object.discount_price.to_f
    = render("field_errors", field: :discount_price, f: f)
    = render("field_errors", field: :discount_price_cents, f: f)
    = render("field_errors", field: :discount_price_currency, f: f)    
  td.form-field
    = link_to_remove_association "×", f, class: 'button remove-element'

api/app/views/admin/application/new.html.slim
- content_for(:title)
  = t( "administrate.actions.new_resource", name: display_resource_name(page.resource_name)).titleize
header.main-content__header role="banner"
  h1.main-content__page-title = content_for(:title)
  div = link_to t("administrate.actions.back"), :back, class: "button"
section.main-content__body = render "form", page: page